/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Architectural Editor Color Palette
        'on-secondary-fixed-variant': '#3a485b',
        'surface-container-low': '#f2f3ff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#dae2fd',
        'on-tertiary-fixed': '#360f00',
        'background': '#faf8ff',
        'tertiary-container': '#bc4800',
        'error': '#ba1a1a',
        'secondary-fixed-dim': '#b9c7df',
        'on-secondary-container': '#57657a',
        'on-primary': '#ffffff',
        'inverse-primary': '#b4c5ff',
        'surface-bright': '#faf8ff',
        'primary-fixed-dim': '#b4c5ff',
        'primary-fixed': '#dbe1ff',
        'on-primary-fixed-variant': '#003ea8',
        'surface-container-high': '#e2e7ff',
        'on-surface': '#131b2e',
        'tertiary-fixed-dim': '#ffb596',
        'on-secondary-fixed': '#0d1c2e',
        'tertiary-fixed': '#ffdbcd',
        'tertiary': '#943700',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'surface-variant': '#dae2fd',
        'secondary-container': '#d5e3fc',
        'on-tertiary-fixed-variant': '#7d2d00',
        'surface-dim': '#d2d9f4',
        'on-primary-container': '#eeefff',
        'on-primary-fixed': '#00174b',
        'on-background': '#131b2e',
        'secondary': '#515f74',
        'primary': '#004ac6',
        'outline': '#737686',
        'inverse-on-surface': '#eef0ff',
        'error-container': '#ffdad6',
        'primary-container': '#2563eb',
        'surface-container': '#eaedff',
        'outline-variant': '#c3c6d7',
        'secondary-fixed': '#d5e3fc',
        'inverse-surface': '#283044',
        'surface-tint': '#0053db',
        'on-surface-variant': '#434655',
        'on-tertiary-container': '#ffede6',
        'surface': '#faf8ff',
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      fontFamily: {
        'headline': ['ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'Helvetica Neue', 'Arial', 'sans-serif'],
        'body': ['ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
        'label': ['ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
      },
      boxShadow: {
        'ambient': '0 20px 40px -12px rgba(19, 27, 46, 0.08)',
      },
    },
  },
  plugins: [],
}
